import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Building2, Check, KeyRound, Mail, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SeraMark, Surface } from "./shared";

export function StudentLogin() { const [mode,setMode]=useState<"access"|"code">("access"); return <AuthFrame title={mode==="access"?"Welcome to your arena.":"Join your institute."} copy={mode==="access"?"Use your institute email or continue with Google.":"Your placement cell shared a short code with you."}>{mode==="access"?<><Button variant="clay" className="h-12 w-full"><span className="text-lg">G</span> Continue with Google</Button><Divider/><Field label="Institute email" placeholder="you@college.edu" icon={Mail}/><Button className="mt-5 h-12 w-full">Send one-time code <ArrowRight/></Button><button onClick={()=>setMode("code")} className="mt-5 w-full text-center text-xs font-medium text-success">I’m joining for the first time</button></>:<><Field label="Institute code" placeholder="PIT-CSE26" icon={KeyRound}/><p className="mt-3 text-xs leading-5 text-muted-foreground">This connects your profile to the right placement team and batch.</p><Button className="mt-6 h-12 w-full" asChild><Link to="/candidate">Continue <ArrowRight/></Link></Button><button onClick={()=>setMode("access")} className="mt-5 w-full text-center text-xs text-muted-foreground">I already have an account</button></>}</AuthFrame> }
export function InstituteLogin() { const [password,setPassword]=useState(false); return <AuthFrame title="Institute workspace" copy="Secure access for placement and career teams."><Field label="Work email" placeholder="placement@institute.edu" icon={Mail}/>{password&&<Field label="Password" placeholder="••••••••" icon={KeyRound} type="password"/>}<Button className="mt-5 h-12 w-full" asChild><Link to="/institute">{password?"Sign in":"Send magic link"}<ArrowRight/></Link></Button><button onClick={()=>setPassword(!password)} className="mt-5 w-full text-center text-xs font-medium text-success">{password?"Use a magic link instead":"Use password instead"}</button>{password&&<button className="mt-3 w-full text-center text-xs text-muted-foreground">Reset password</button>}</AuthFrame> }
export function AcceptInvite(){return <AuthFrame title="You’re invited." copy="Pioneer Institute of Technology has invited you to Sera Interview Arena."><Surface inset className="p-5"><div className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-full bg-blue-soft"><Building2 className="size-5 text-blue-foreground"/></span><div><p className="text-sm font-medium">Pioneer Institute of Technology</p><p className="text-xs text-muted-foreground">CSE 2026 · Student access</p></div></div></Surface><div className="my-6 space-y-3 text-xs text-muted-foreground"><p className="flex gap-2"><Check className="size-4 text-success"/>Build your interview profile</p><p className="flex gap-2"><Check className="size-4 text-success"/>Complete four simulated rounds</p><p className="flex gap-2"><ShieldCheck className="size-4 text-success"/>Your institute sees scores and summaries</p></div><Button className="h-12 w-full" asChild><Link to="/student-login">Accept invite <ArrowRight/></Link></Button></AuthFrame>}
function AuthFrame({title,copy,children}:{title:string;copy:string;children:React.ReactNode}) { return <main className="grid min-h-screen place-items-center px-5 py-12"><div className="w-full max-w-md"><Link to="/login" className="mb-8 inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft className="size-3"/>Back</Link><div className="mb-8"><SeraMark/><h1 className="mt-10 text-3xl font-medium">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{copy}</p></div><Surface className="p-6 sm:p-8">{children}</Surface><p className="mt-6 text-center text-[11px] text-muted-foreground">By continuing, you agree to the institute’s Arena participation policy.</p></div></main> }
function Field({label,placeholder,icon:Icon,type="text"}:{label:string;placeholder:string;icon:typeof UserRound;type?:string}) { return <label className="mt-4 block text-xs font-medium">{label}<span className="clay-inset mt-2 flex items-center gap-3 rounded-xl px-4"><Icon className="size-4 text-muted-foreground"/><input type={type} placeholder={placeholder} className="h-12 w-full bg-transparent text-sm outline-none"/></span></label> }
function Divider(){return <div className="my-6 flex items-center gap-3 text-[10px] text-muted-foreground"><span className="h-px flex-1 bg-border"/>OR<span className="h-px flex-1 bg-border"/></div>}