import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, BarChart3, Building2, Check, ChevronDown, FileText, Mic2, ShieldCheck, Target, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SeraMark, Surface } from "./shared";

const rounds = [
  { n: "01", title: "Sera screening", copy: "A focused five-minute voice conversation to understand your story.", color: "bg-sage" },
  { n: "02", title: "HR BP round", copy: "Culture, confidence, expectations and consistency with your CV.", color: "bg-amber-soft" },
  { n: "03", title: "Functional", copy: "Aptitude first, then a role-specific interview built around your answers.", color: "bg-rose-soft" },
  { n: "04", title: "CEO round", copy: "A final leadership conversation that can end with a simulated offer.", color: "bg-blue-soft" },
];

export function PublicSite() {
  const [faq, setFaq] = useState(0);
  return <main className="min-h-screen overflow-hidden">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 lg:px-10"><SeraMark /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#journey">The journey</a><a href="#institutes">For institutes</a><a href="#faq">FAQ</a></nav><Button asChild variant="clay"><Link to="/login">Sign in <ArrowRight /></Link></Button></header>
    <section className="mx-auto grid min-h-[76vh] max-w-7xl items-center gap-14 px-5 pb-16 pt-10 lg:grid-cols-[1.08fr_.92fr] lg:px-10">
      <div><div className="mb-7 inline-flex items-center gap-2 text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground"><span className="size-2 rounded-full bg-success" /> Interview readiness, made visible</div><h1 className="max-w-3xl text-5xl font-medium leading-[1.03] sm:text-6xl lg:text-7xl">Practise the interview.<br/><span className="text-success">Understand the result.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">A four-round interview arena that turns every answer into specific evidence, a practical roadmap, and a readiness report.</p><div className="mt-9 flex flex-wrap gap-4"><Button size="lg" asChild><Link to="/student-login">Student login <ArrowRight /></Link></Button><Button size="lg" variant="clay" asChild><Link to="/institute-login">Institute login</Link></Button></div><div className="mt-10 flex flex-wrap gap-6 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Check className="size-4 text-success" />Four realistic rounds</span><span className="flex items-center gap-2"><Check className="size-4 text-success" />Evidence-led feedback</span><span className="flex items-center gap-2"><Check className="size-4 text-success" />No grades, only growth</span></div></div>
      <div className="relative mx-auto w-full max-w-lg py-8"><Surface className="relative p-7 sm:p-9"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Readiness report</p><h2 className="mt-1 text-xl font-medium">Riya Kulkarni</h2></div><span className="rounded-full bg-sage/50 px-3 py-1 text-xs font-medium text-success">Offer ready</span></div><div className="my-10 flex items-center justify-center"><div className="relative grid size-52 place-items-center rounded-full bg-sage shadow-[var(--shadow-inset)]"><div className="grid size-40 place-items-center rounded-full bg-background shadow-[var(--shadow-raised)]"><div className="text-center"><strong className="text-5xl font-medium">74</strong><div className="mt-1 text-xs text-muted-foreground">Overall readiness</div></div></div></div></div><div className="grid grid-cols-4 gap-3">{rounds.map((r) => <div key={r.n} className="text-center"><div className={`mx-auto mb-2 h-1.5 rounded-full ${r.color}`} /><span className="text-xs text-muted-foreground">{r.title.split(" ")[0]}</span></div>)}</div></Surface><div className="absolute -right-5 top-20 hidden rounded-2xl bg-background p-4 shadow-[var(--shadow-raised)] sm:block"><Target className="mb-2 size-5 text-success"/><p className="text-xs text-muted-foreground">Company match</p><p className="text-sm font-medium">82% · Northwind</p></div></div>
    </section>
    <section id="journey" className="bg-secondary/45 py-24"><div className="mx-auto max-w-7xl px-5 lg:px-10"><p className="text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground">One coherent journey</p><h2 className="mt-4 max-w-2xl text-3xl font-medium sm:text-4xl">Four rounds. One clear picture of where you stand.</h2><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{rounds.map((r) => <Surface key={r.n} className="p-6"><div className={`mb-12 grid size-11 place-items-center rounded-full ${r.color} text-sm font-medium`}>{r.n}</div><h3 className="font-medium">{r.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{r.copy}</p></Surface>)}</div></div></section>
    <section id="institutes" className="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-2 lg:px-10"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground">For placement teams</p><h2 className="mt-4 text-4xl font-medium">See the cohort, not just the count.</h2><p className="mt-5 max-w-lg leading-7 text-muted-foreground">Track readiness by round, find common weak areas, and turn student evidence into focused training plans.</p><div className="mt-8 space-y-5">{([{Icon:BarChart3,text:"Cohort readiness and improvement"},{Icon:FileText,text:"Individual and batch-ready reports"},{Icon:ShieldCheck,text:"Institute-scoped, consent-aware access"}]).map(({Icon,text}) => <div className="flex items-center gap-4" key={text}><span className="clay-soft grid size-11 place-items-center rounded-xl"><Icon className="size-5 text-success" /></span><span className="text-sm font-medium">{text}</span></div>)}</div><Button className="mt-9" asChild><Link to="/institute">Open institute preview <ArrowRight /></Link></Button></div><Surface className="p-7"><div className="flex items-center gap-3"><Building2 className="size-5 text-success"/><span className="font-medium">Placement readiness · CSE 2026</span></div><div className="mt-7 grid grid-cols-3 gap-3">{[["84%","Started"],["68%","Completed"],["71","Avg. readiness"]].map(([v,l]) => <div className="clay-inset rounded-xl p-4 text-center" key={l}><strong className="text-xl font-medium">{v}</strong><p className="mt-1 text-[11px] text-muted-foreground">{l}</p></div>)}</div><div className="mt-8 space-y-4">{[["Profile complete",92],["Screening",84],["HR BP",72],["Functional",61],["CEO round",38],["Offer",24]].map(([l,v]) => <div key={l as string}><div className="mb-1.5 flex justify-between text-xs"><span>{l}</span><span className="text-muted-foreground">{v}%</span></div><div className="h-2 rounded-full bg-background shadow-[var(--shadow-inset)]"><div className="h-2 rounded-full bg-sage" style={{width:`${v}%`}} /></div></div>)}</div></Surface></section>
    <section id="faq" className="bg-secondary/45 py-24"><div className="mx-auto max-w-3xl px-5"><h2 className="text-center text-3xl font-medium">Questions, answered simply.</h2><div className="mt-10 space-y-3">{[["Is this a real job offer?","No. The offer is a realistic simulation designed to show interview readiness."],["Can students retry a round?","A failed round gets one retry. The new result replaces the earlier score while the attempt stays in history."],["What can institute staff see?","Staff see their own institute’s students, scores and summaries. Transcript access requires student consent."]].map(([q,a],i)=><Surface key={q} className="overflow-hidden"><button className="flex w-full items-center justify-between p-5 text-left text-sm font-medium" onClick={()=>setFaq(faq===i?-1:i)}>{q}<ChevronDown className={`size-4 transition-transform ${faq===i?"rotate-180":""}`} /></button>{faq===i&&<p className="px-5 pb-5 text-sm leading-6 text-muted-foreground">{a}</p>}</Surface>)}</div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 text-xs text-muted-foreground sm:flex-row sm:items-center lg:px-10"><SeraMark compact /><span>© 2026 YZI Works. Built for better placement conversations.</span><span className="sm:ml-auto">Privacy · Accessibility · Support</span></footer>
  </main>;
}

export function LoginChoice() {
  return <main className="grid min-h-screen place-items-center px-5 py-12"><div className="w-full max-w-3xl"><div className="mb-12 text-center"><div className="flex justify-center"><SeraMark /></div><h1 className="mt-8 text-3xl font-medium">Choose your space</h1><p className="mt-2 text-sm text-muted-foreground">The right view, the right level of detail.</p></div><div className="grid gap-5 sm:grid-cols-2"><Surface className="p-7"><UserRound className="size-7 text-success"/><h2 className="mt-8 text-xl font-medium">I’m a student</h2><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">Build your profile, enter the arena, and understand your readiness.</p><Button className="mt-7 w-full" asChild><Link to="/student-login">Continue as student <ArrowRight /></Link></Button><p className="mt-4 text-center text-xs text-muted-foreground">Institute code required for new accounts</p></Surface><Surface className="p-7"><Building2 className="size-7 text-blue-foreground"/><h2 className="mt-8 text-xl font-medium">I’m with an institute</h2><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">See student progress, cohort patterns, and placement-ready reports.</p><Button className="mt-7 w-full" asChild><Link to="/institute-login">Continue as institute <ArrowRight /></Link></Button><p className="mt-4 text-center text-xs text-muted-foreground">Magic link or password access</p></Surface></div><Link to="/" className="mt-8 block text-center text-sm text-muted-foreground">Back to Sera</Link></div></main>;
}